### ISSUE TITLE
Split leaderboard into public and private

### ISSUE THREAD

**Issue by jmleroux** [the-badger/badger#110]
After a discussion with G. Planchat, he told me that the leaderboard could be frustating for contributors because they cannot earn as much badges as we can, and so do not have a chance be in the leaderboard.
We maybe could make two leaderboards: one for internal people and one for all people but counting only public badges.

**Comment by jmleroux** [comment]
To be closed. I think it is done.
ping @grena

**Comment by grena** [comment]
No unfortunately, the leaderboard take all badges, regardless the tag :(
So this issue is still relevant!
