### ISSUE TITLE
Automatic badge claim with a "code"

### ISSUE THREAD

**Issue by mickaelandrieu** [the-badger/badger#157]
Hello,

what I'd like to do is to give a badge after a survey completion by a community member without the wait for any "human" intervention from Badger team.

To do that, I need to be able to provide a unique code (which can be used only once) for each respondent, or maybe we can start simple and provide a code for some badges.

In this cases, it's easier we could have a link like ``http://badger.akeneo.com/claim/<code>`` and if the user is logged the badge is activated.

What do you think?

**Comment by grena** [comment]
We'll do a hook for this kind of stuff :)
cf. #28
